version: "3"
services:
  mysql:
    image: mysql:8.0.28-debian
    container_name: django_todolist_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: django-password
      MYSQL_USER: django-user
      MYSQL_DATABASE: django-todolist
    ports:
      - 3306:3306
    networks:
      - djangotodolistnetwork

  adminer:
    image: adminer
    container_name: django_todolist_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - djangotodolistnetwork

  app:
    build:
      context: .
    container_name: django_todolist_app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      - MYSQL_NAME=django-todolist
      - MYSQL_USER=django-user
      - MYSQL_PASSWORD=django-password
      - MYSQL_HOST=django_todolist_mysql
    networks:
      - djangotodolistnetwork

networks:
  djangotodolistnetwork:
