# Generated by Django 3.1.7 on 2021-02-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('inreview', 'In Review'), ('finished', 'Finished')], default='todo', max_length=10),
        ),
    ]
