# Generated by Django 3.1.7 on 2021-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210225_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('inreview', 'In Review'), ('done', 'Done')], default='todo', max_length=10),
        ),
    ]
